export type ColorPalette = {
  name: string
  label: string
  colors: {
    background: string
    foreground: string
    card: string
    cardForeground: string
    popover: string
    popoverForeground: string
    primary: string
    primaryForeground: string
    primaryHover: string
    secondary: string
    secondaryForeground: string
    muted: string
    mutedForeground: string
    accent: string
    accentForeground: string
    border: string
    input: string
    ring: string
  }
  preview: string
  pattern?: boolean
}

export const colorPalettes: Record<string, ColorPalette> = {
  'dark-purple': {
    name: 'dark-purple',
    label: 'Dark Purple',
    colors: {
      background: '#000000',
      foreground: '#ffffff',
      card: '#18181b',
      cardForeground: '#ffffff',
      popover: '#18181b',
      popoverForeground: '#ffffff',
      primary: '#8b5cf6',
      primaryForeground: '#ffffff',
      primaryHover: '#7c3aed',
      secondary: '#0a0a0a',
      secondaryForeground: '#ffffff',
      muted: '#18181b',
      mutedForeground: '#a1a1aa',
      accent: '#18181b',
      accentForeground: '#ffffff',
      border: '#27272a',
      input: '#18181b',
      ring: '#8b5cf6',
    },
    preview: 'from-black via-purple-950 to-purple-900',
  },
  'dark-blue': {
    name: 'dark-blue',
    label: 'Dark Blue',
    colors: {
      background: '#0c1222',
      foreground: '#f1f5f9',
      card: '#1e293b',
      cardForeground: '#f1f5f9',
      popover: '#1e293b',
      popoverForeground: '#f1f5f9',
      primary: '#3b82f6',
      primaryForeground: '#ffffff',
      primaryHover: '#2563eb',
      secondary: '#0f172a',
      secondaryForeground: '#f1f5f9',
      muted: '#1e293b',
      mutedForeground: '#94a3b8',
      accent: '#1e293b',
      accentForeground: '#f1f5f9',
      border: '#334155',
      input: '#1e293b',
      ring: '#3b82f6',
    },
    preview: 'from-slate-950 via-blue-950 to-blue-900',
  },
  'warm-dark': {
    name: 'warm-dark',
    label: 'Warm Dark',
    colors: {
      background: '#1a0f0a',
      foreground: '#fef3e2',
      card: '#2d1f17',
      cardForeground: '#fef3e2',
      popover: '#2d1f17',
      popoverForeground: '#fef3e2',
      primary: '#f97316',
      primaryForeground: '#ffffff',
      primaryHover: '#ea580c',
      secondary: '#1c1410',
      secondaryForeground: '#fef3e2',
      muted: '#2d1f17',
      mutedForeground: '#d4b896',
      accent: '#2d1f17',
      accentForeground: '#fef3e2',
      border: '#3d2b20',
      input: '#2d1f17',
      ring: '#f97316',
    },
    preview: 'from-orange-950 via-amber-950 to-yellow-900',
  },
  'forest': {
    name: 'forest',
    label: 'Forest',
    colors: {
      background: '#0a1410',
      foreground: '#e8f5e9',
      card: '#1a2820',
      cardForeground: '#e8f5e9',
      popover: '#1a2820',
      popoverForeground: '#e8f5e9',
      primary: '#10b981',
      primaryForeground: '#ffffff',
      primaryHover: '#059669',
      secondary: '#0f1a15',
      secondaryForeground: '#e8f5e9',
      muted: '#1a2820',
      mutedForeground: '#a5c9b0',
      accent: '#1a2820',
      accentForeground: '#e8f5e9',
      border: '#2d3f35',
      input: '#1a2820',
      ring: '#10b981',
    },
    preview: 'from-emerald-950 via-green-950 to-teal-900',
  },
  'rose': {
    name: 'rose',
    label: 'Rose',
    colors: {
      background: '#1a0a14',
      foreground: '#fce7f3',
      card: '#2d1825',
      cardForeground: '#fce7f3',
      popover: '#2d1825',
      popoverForeground: '#fce7f3',
      primary: '#ec4899',
      primaryForeground: '#ffffff',
      primaryHover: '#db2777',
      secondary: '#1f0f1a',
      secondaryForeground: '#fce7f3',
      muted: '#2d1825',
      mutedForeground: '#f9a8d4',
      accent: '#2d1825',
      accentForeground: '#fce7f3',
      border: '#3d2535',
      input: '#2d1825',
      ring: '#ec4899',
    },
    preview: 'from-pink-950 via-rose-950 to-fuchsia-900',
  },
  'ocean': {
    name: 'ocean',
    label: 'Ocean',
    colors: {
      background: '#0a1419',
      foreground: '#e0f2fe',
      card: '#1a2830',
      cardForeground: '#e0f2fe',
      popover: '#1a2830',
      popoverForeground: '#e0f2fe',
      primary: '#06b6d4',
      primaryForeground: '#ffffff',
      primaryHover: '#0891b2',
      secondary: '#0f1a20',
      secondaryForeground: '#e0f2fe',
      muted: '#1a2830',
      mutedForeground: '#7dd3fc',
      accent: '#1a2830',
      accentForeground: '#e0f2fe',
      border: '#2d3f4a',
      input: '#1a2830',
      ring: '#06b6d4',
    },
    preview: 'from-cyan-950 via-sky-950 to-blue-900',
  },
  'sand-light': {
    name: 'sand-light',
    label: 'Sand Light',
    colors: {
      background: '#faf8f5',
      foreground: '#3d3929',
      card: '#ffffff',
      cardForeground: '#3d3929',
      popover: '#ffffff',
      popoverForeground: '#3d3929',
      primary: '#d97706',
      primaryForeground: '#ffffff',
      primaryHover: '#b45309',
      secondary: '#f5f1eb',
      secondaryForeground: '#3d3929',
      muted: '#f5f1eb',
      mutedForeground: '#8b7f6a',
      accent: '#f5f1eb',
      accentForeground: '#3d3929',
      border: '#e8dfd0',
      input: '#ffffff',
      ring: '#d97706',
    },
    preview: 'from-amber-50 via-orange-100 to-yellow-100',
  },
  'mauve-light': {
    name: 'mauve-light',
    label: 'Mauve Light',
    colors: {
      background: '#faf8fb',
      foreground: '#3d2e3d',
      card: '#ffffff',
      cardForeground: '#3d2e3d',
      popover: '#ffffff',
      popoverForeground: '#3d2e3d',
      primary: '#a855f7',
      primaryForeground: '#ffffff',
      primaryHover: '#9333ea',
      secondary: '#f5f0f7',
      secondaryForeground: '#3d2e3d',
      muted: '#f5f0f7',
      mutedForeground: '#8b7a8b',
      accent: '#f5f0f7',
      accentForeground: '#3d2e3d',
      border: '#e8dce8',
      input: '#ffffff',
      ring: '#a855f7',
    },
    preview: 'from-purple-50 via-fuchsia-100 to-pink-100',
  },
  'sky-light': {
    name: 'sky-light',
    label: 'Sky Light',
    colors: {
      background: '#f8fafb',
      foreground: '#2e3d4d',
      card: '#ffffff',
      cardForeground: '#2e3d4d',
      popover: '#ffffff',
      popoverForeground: '#2e3d4d',
      primary: '#0ea5e9',
      primaryForeground: '#ffffff',
      primaryHover: '#0284c7',
      secondary: '#f0f5f7',
      secondaryForeground: '#2e3d4d',
      muted: '#f0f5f7',
      mutedForeground: '#6b8299',
      accent: '#f0f5f7',
      accentForeground: '#2e3d4d',
      border: '#dce8ed',
      input: '#ffffff',
      ring: '#0ea5e9',
    },
    preview: 'from-sky-50 via-blue-100 to-cyan-100',
  },
  'sage-light': {
    name: 'sage-light',
    label: 'Sage Light',
    colors: {
      background: '#f8faf9',
      foreground: '#2e3d32',
      card: '#ffffff',
      cardForeground: '#2e3d32',
      popover: '#ffffff',
      popoverForeground: '#2e3d32',
      primary: '#059669',
      primaryForeground: '#ffffff',
      primaryHover: '#047857',
      secondary: '#f0f5f2',
      secondaryForeground: '#2e3d32',
      muted: '#f0f5f2',
      mutedForeground: '#6b8270',
      accent: '#f0f5f2',
      accentForeground: '#2e3d32',
      border: '#dce8e0',
      input: '#ffffff',
      ring: '#059669',
    },
    preview: 'from-emerald-50 via-green-100 to-teal-100',
  },
  'classic-light': {
    name: 'classic-light',
    label: 'Classic Light',
    colors: {
      background: '#ffffff',
      foreground: '#111827',
      card: '#ffffff',
      cardForeground: '#111827',
      popover: '#ffffff',
      popoverForeground: '#111827',
      primary: '#8b5cf6',
      primaryForeground: '#ffffff',
      primaryHover: '#7c3aed',
      secondary: '#f9fafb',
      secondaryForeground: '#111827',
      muted: '#f9fafb',
      mutedForeground: '#6b7280',
      accent: '#f9fafb',
      accentForeground: '#111827',
      border: '#e5e7eb',
      input: '#ffffff',
      ring: '#8b5cf6',
    },
    preview: 'from-gray-50 via-slate-100 to-zinc-100',
  },
  'playful-pets': {
    name: 'playful-pets',
    label: 'Playful Pets',
    colors: {
      background: '#0a0a0a',
      foreground: '#ffffff',
      card: '#1a1a1a',
      cardForeground: '#ffffff',
      popover: '#1a1a1a',
      popoverForeground: '#ffffff',
      primary: '#f59e0b',
      primaryForeground: '#000000',
      primaryHover: '#d97706',
      secondary: '#0f0f0f',
      secondaryForeground: '#ffffff',
      muted: '#1a1a1a',
      mutedForeground: '#a1a1aa',
      accent: '#1a1a1a',
      accentForeground: '#ffffff',
      border: '#2a2a2a',
      input: '#1a1a1a',
      ring: '#f59e0b',
    },
    preview: 'from-amber-600 via-orange-500 to-yellow-500',
    pattern: true,
  },
}

export const defaultPalette = 'classic-light'
