// Mock for jose module
module.exports = {
  compactDecrypt: jest.fn(),
  compactEncrypt: jest.fn(),
  compactVerify: jest.fn(),
  CompactEncrypt: jest.fn(),
  CompactSign: jest.fn(),
  createLocalJWKSet: jest.fn(),
  createRemoteJWKSet: jest.fn(),
  decodeJwt: jest.fn(),
  decodeProtectedHeader: jest.fn(),
  exportJWK: jest.fn(),
  exportPKCS8: jest.fn(),
  exportSPKI: jest.fn(),
  FlattenedDecrypt: jest.fn(),
  FlattenedEncrypt: jest.fn(),
  FlattenedSign: jest.fn(),
  flattenedVerify: jest.fn(),
  generateKeyPair: jest.fn(),
  generateSecret: jest.fn(),
  importJWK: jest.fn(),
  importPKCS8: jest.fn(),
  importSPKI: jest.fn(),
  importX509: jest.fn(),
  jwtDecrypt: jest.fn(),
  JWTDecrypt: jest.fn(),
  jwtVerify: jest.fn(),
  JWTVerify: jest.fn()
};
